#!/usr/bin/env bash
# Generates snippets/emby-api-keys.conf (the nginx 'map' constants holding
# the real TMDB/MDBList/Kinopoisk keys) WITHOUT ever printing a key.
#
# Source of the keys, in order of preference:
#   --from-truenas   read secrets/api.env on the TrueNAS host over SSH
#                    (deploy/truenas-ssh.sh; the file the installer validated)
#   --from-env FILE  read TMDB_API_KEY/MDBLIST_API_KEY/KINOPOISK_API_KEY from
#                    a local KEY=value file (e.g. deploy/truenas.env)
#
# Output: the path given with --out (default: a mktemp file, chmod 600).
# Copy it to /etc/nginx/snippets/emby-api-keys.conf on the nginx host and
# keep it chmod 600 (deploy/nginx/install.sh does that).
set -Eeuo pipefail
HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

MODE=""; ENV_FILE=""; OUT=""
while [ "$#" -gt 0 ]; do
    case "$1" in
        --from-truenas) MODE="truenas"; shift ;;
        --from-env) MODE="env"; ENV_FILE="$2"; shift 2 ;;
        --out) OUT="$2"; shift 2 ;;
        *) echo "usage: $0 (--from-truenas | --from-env FILE) [--out PATH]" >&2; exit 2 ;;
    esac
done
[ -n "$MODE" ] || { echo "usage: $0 (--from-truenas | --from-env FILE) [--out PATH]" >&2; exit 2; }

TMDB=""; MDBLIST=""; KINOPOISK=""
case "$MODE" in
    truenas)
        # Only the three values travel back, newline-separated, never echoed here.
        # shellcheck disable=SC2016
        IFS=$'\n' read -r -d '' TMDB MDBLIST KINOPOISK < <("$HERE/../truenas-ssh.sh" -- 'source /mnt/toolbox/configs/emby/secrets/api.env 2>/dev/null || source "$(ls /mnt/*/configs/emby/secrets/api.env 2>/dev/null | head -1)"; printf "%s\n%s\n%s\n" "${TMDB_API_KEY:-}" "${MDBLIST_API_KEY:-}" "${KINOPOISK_API_KEY:-}"; printf "\0"') || true
        ;;
    env)
        [ -r "$ENV_FILE" ] || { echo "cannot read $ENV_FILE" >&2; exit 1; }
        # shellcheck disable=SC1090
        source "$ENV_FILE"
        TMDB="${TMDB_API_KEY:-}"; MDBLIST="${MDBLIST_API_KEY:-}"; KINOPOISK="${KINOPOISK_API_KEY:-}"
        ;;
esac

[ -n "$TMDB" ] || { echo "TMDB_API_KEY is empty: refusing to write a keys file without it" >&2; exit 1; }
# TMDB v3 keys are 32 hex chars; a 200+ char value is the v4 read token, which the addons cannot use.
[ "${#TMDB}" = "32" ] || echo "warning: TMDB_API_KEY has ${#TMDB} characters (a v3 API key has 32; the v4 read-access token does not work with api_key=)" >&2

[ -n "$OUT" ] || OUT="$(mktemp)"
umask 077
{
    echo "# Real third-party API keys for snippets/emby-api-proxy.conf -- generated by deploy/nginx/render-keys.sh ($MODE)."
    echo "# Keep chmod 600. nginx reads it as root at start/reload; workers never need it."
    printf 'map $host $emby_tmdb_api_key      { default "%s"; }\n' "$TMDB"
    printf 'map $host $emby_mdblist_api_key   { default "%s"; }\n' "$MDBLIST"
    printf 'map $host $emby_kinopoisk_api_key { default "%s"; }\n' "$KINOPOISK"
} > "$OUT"
chmod 600 "$OUT"
echo "written: $OUT (tmdb ${#TMDB} chars, mdblist ${#MDBLIST} chars, kinopoisk ${#KINOPOISK} chars)"
