#!/usr/bin/env bash
# Watchdog for the installed customizations: if the Emby container was
# recreated (image update, app reinstall) its /system is stock again, so the
# addons, the theme entry in skinmanager.js and the index.html <script> tags
# are gone. This script notices and runs the newest reapply-<timestamp>.sh
# generated by install-emby-custom.sh. Meant for cron on the Emby host
# (TrueNAS: System Settings -> Advanced -> Cron Jobs), e.g. every 15 min:
#
#   /mnt/toolbox/scripts/emby-reapply-watchdog.sh --container ix-emby-emby-1 --custom /mnt/toolbox/configs/emby/custom
#
# Checks (any failing one triggers the reapply):
#   1. every addon listed in the newest manifest exists in the container;
#   2. index.html references every addon;
#   3. if the last install used theme mode, skinmanager.js contains the
#      theme entry and theme.css exists.
# Exit 0 = healthy or reapplied OK; 1 = reapply failed; 2 = usage/precondition.
# Logs to <custom>/watchdog.log. Never downloads anything: reapply re-copies
# what is already staged under <custom>/dashboard-ui/.
set -Eeuo pipefail

CONTAINER=""; CUSTOM=""; DRY=0
while [ "$#" -gt 0 ]; do
    case "$1" in
        --container) CONTAINER="$2"; shift 2 ;;
        --custom) CUSTOM="$2"; shift 2 ;;
        --dry-run) DRY=1; shift ;;
        *) echo "usage: $0 --container NAME --custom /path/to/emby/custom [--dry-run]" >&2; exit 2 ;;
    esac
done
[ -n "$CONTAINER" ] && [ -n "$CUSTOM" ] || { echo "usage: $0 --container NAME --custom /path/to/emby/custom [--dry-run]" >&2; exit 2; }

LOG="$CUSTOM/watchdog.log"
log() { printf '%s %s\n' "$(date '+%Y-%m-%d %H:%M:%S')" "$*" | tee -a "$LOG"; }

MANIFEST="$(ls -t "$CUSTOM"/manifest-*.json 2>/dev/null | head -1 || true)"
REAPPLY="$(ls -t "$CUSTOM"/reapply-*.sh 2>/dev/null | head -1 || true)"
[ -n "$MANIFEST" ] && [ -n "$REAPPLY" ] || { log "no manifest/reapply under $CUSTOM: nothing to watch"; exit 2; }
grep -q '"install_result": "SUCCESS"' "$MANIFEST" || { log "last manifest is not SUCCESS ($MANIFEST): not reapplying automatically"; exit 2; }

docker inspect "$CONTAINER" >/dev/null 2>&1 || { log "container $CONTAINER not found"; exit 2; }
[ "$(docker inspect "$CONTAINER" -f '{{.State.Running}}')" = "true" ] || { log "container $CONTAINER not running; will check again next run"; exit 0; }

DASH=/system/dashboard-ui
PROBLEMS=()
# Addons from the manifest "files" array (one per line, quoted).
while IFS= read -r js; do
    docker exec "$CONTAINER" sh -c "test -s '$DASH/$js'" 2>/dev/null || PROBLEMS+=("missing $js")
    docker exec "$CONTAINER" sh -c "grep -qF '$js' '$DASH/index.html'" 2>/dev/null || PROBLEMS+=("index.html lacks $js")
done < <(awk '/"files": \[/{f=1;next} f&&/\]/{exit} f{gsub(/[",[:space:]]/,""); if($0!="")print}' "$MANIFEST")

if grep -q '"mode": "theme"' "$MANIFEST"; then
    docker exec "$CONTAINER" sh -c "grep -qF 'id:\"embymalism\"' '$DASH/modules/skinmanager.js'" 2>/dev/null || PROBLEMS+=("theme entry missing in skinmanager.js")
    docker exec "$CONTAINER" sh -c "test -s '$DASH/modules/themes/embymalism/theme.css'" 2>/dev/null || PROBLEMS+=("theme.css missing")
fi

if [ "${#PROBLEMS[@]}" -eq 0 ]; then
    log "healthy: customizations present in $CONTAINER"
    exit 0
fi

log "drift detected: ${PROBLEMS[*]}"
if [ "$DRY" = "1" ]; then
    log "dry-run: would run $REAPPLY"
    exit 0
fi
log "running $REAPPLY"
if bash "$REAPPLY" >> "$LOG" 2>&1; then
    log "reapply finished OK"
    exit 0
else
    rc=$?
    log "reapply exited with $rc (see above in this log)"
    exit 1
fi
